---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qaroot-frontend

  labels:
    app: qaroot-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qaroot-frontend
  template:
    metadata:
      labels:
        app: qaroot-frontend
    spec:
      containers:
      - name: frontend
        image: quay.io/hayesphilip/qaroot-frontend:latest
        ports:
        - containerPort: 8080
          name: http
        # No environment variables needed - nginx proxies to internal services
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qaroot-frontend

  labels:
    app: qaroot-frontend
spec:
  selector:
    app: qaroot-frontend
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qaroot-frontend

  labels:
    app: qaroot-frontend
spec:
  to:
    kind: Service
    name: qaroot-frontend
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
