---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qaroot-websocket-service
  namespace: qaroot-mvp
  labels:
    app: qaroot-websocket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qaroot-websocket-service
  template:
    metadata:
      labels:
        app: qaroot-websocket-service
    spec:
      containers:
      - name: websocket-service
        image: quay.io/hayesphilip/qaroot-websocket-service:latest
        ports:
        - containerPort: 3001
          name: websocket
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "3001"
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: database
        - name: DATABASE_URL
          value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@postgresql:5432/$(DATABASE_NAME)"
        - name: REDIS_URL
          value: redis://redis:6379
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-credentials
              key: jwt-secret
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 500m
        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qaroot-websocket-service
  namespace: qaroot-mvp
  labels:
    app: qaroot-websocket-service
spec:
  selector:
    app: qaroot-websocket-service
  ports:
  - name: websocket
    port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qaroot-websocket
  namespace: qaroot-mvp
  labels:
    app: qaroot-websocket-service
spec:
  to:
    kind: Service
    name: qaroot-websocket-service
  port:
    targetPort: websocket
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  websockets: true
